### ISSUE TITLE
appmap-node command fails, presumably due to Windows path issue

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-node#122]
![Screenshot (33)](https://github.com/getappmap/appmap-node/assets/86395/2da2799f-bd1b-42a0-9dbb-de4e3be5219c)

![Screenshot (32)](https://github.com/getappmap/appmap-node/assets/86395/4fed0a71-c656-401f-aa46-033795000a3b)

**Comment by dividedmind** [comment]
Could this be related to a space in the user home directory path? Nb, I tried reproducing this by putting both appmap-node and the target project on a space-containing path on Linux, but it works for me. Perhaps there is something else going on or the problem is Windows-specific.

**Comment by dividedmind** [comment]
Another user saw this, they say they definitely didn't have a space in the path, so this must be something else. In case it's relevant, the OP was running Node 20.11.

**Comment by zermelo-wisen** [comment]
Steps to reproduce:

- Set up a Windows environment (e.g., create a Windows VPS on AWS)
- Create a user with a space in the user name: “John Doe”
- Switch to the new user
- Install Node to the default location
- `npm init` a trivial project
- Run `npx app map-node rpm run test`

This will result in the reported error. It seems that the issue lies in the npm cache path, which contains a space from the username.

```
npm config get cache
C:\Users\John Doe\AppData\Local\npm-cache
```

To resolve this, eliminate the space in the npm cache path:
```
npm config set cache "C:\Users\John~1\AppData\Roaming\npm-cache" --global
```
This should resolve the issue.

Similar issue is reported with different packages run with npx. Most relevant one is this: https://stackoverflow.com/questions/58354348/windows-10-npx-create-react-app-myapp-command-does-not-work-because-of-whit.

**Comment by kgilpin** [comment]
Let’s add to our docs on appmap.io

**Comment by dividedmind** [comment]
Seems like another workaround is to `npm install -g npm@7`: https://github.com/npm/cli/issues/502

**Comment by dividedmind** [comment]
@zermelo-wisen, could you verify `npm install -g npm@7` indeed fixes the problem?

**Comment by zermelo-wisen** [comment]
> @zermelo-wisen, could you verify `npm install -g npm@7` indeed fixes the problem?

I tried it, unfortunately not. npm@7 is an old version now anyway.

<img width="639" alt="image" src="https://github.com/getappmap/appmap-node/assets/98758224/eabc9af5-e566-4839-9aeb-86db81869d51">

**Comment by dividedmind** [comment]
> > @zermelo-wisen, could you verify `npm install -g npm@7` indeed fixes the problem?
> 
> I tried it, unfortunately not. npm@7 is an old version now anyway.

Yeah, I suspected as much :/ Thanks for checking. Did you find a current bug report in npx for this issue? Because it seems https://github.com/npm/cli/issues/502 is old.

**Comment by zermelo-wisen** [comment]
I checked the issues list, but couldn't find any.
